name: Context testing
on:
  pull_request:
    types:
      - closed

jobs:
  dump_github_context_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'