name: Bump

on:
  push:
    branches:
      - master

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update readme
        run: echo "DATE = $(date)" >> README.md

      - name: Commit and tag the new version
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automatic bump after merge"
          file_pattern: README.md
          commit_author: Github Action <actions@github.com>
          commit_user_name: github-actions
          create_branch: false